apiVersion: v1
kind: Pod
metadata:
  name: curlpod
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 10; done;"]
    volumeMounts:
    - mountPath: /tls-data
      name: tls-volume
  volumes:
  - name: tls-volume
    hostPath:
      # directory location on host
      path: /tls-data
