apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /tls-data
          name: tls-volume

      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9121
        volumeMounts:
        - mountPath: /tls-data
          name: tls-volume
        env:
        - name: REDIS_EXPORTER_DEBUG
          value: 'true'
        - name: REDIS_EXPORTER_NAMESPACE
          value: ''
        # # - name: REDIS_EXPORTER_SKIP_TLS_VERIFICATION
        # #   value: 'true'
        # - name: REDIS_EXPORTER_TLS_CLIENT_KEY_FILE
        #   value: /tls-data/xx
        # - name: REDIS_EXPORTER_TLS_CLIENT_CERT_FILE
        #   value: /tls-data/xx
        # - name: REDIS_EXPORTER_TLS_SERVER_KEY_FILE
        #   value: /tls-data/xx
        # - name: REDIS_EXPORTER_TLS_SERVER_CERT_FILE
        #   value: /tls-data/xx
        # - name: REDIS_EXPORTER_TLS_CA_CERT_FILE
        #   value: /tls-data/xx

      volumes:
      - name: tls-volume
        hostPath:
          # directory location on host
          path: /tls-data
