kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
nodes:
- role: control-plane
  # Add a mount from the host to the kind node
  extraMounts:
  - hostPath: /tmp/tls-data
    containerPath: /tls-data
